name: currencie_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
 sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_local_notifications: ^19.0.0
  firebase_messaging: ^15.2.4
  provider: ^6.1.1
  shared_preferences: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  connectivity_plus: ^4.0.1
  flex_color_scheme: ^7.1.2
  animated_toggle_switch: ^0.5.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "icon.png" # Path to your new app icon
  adaptive_icon_background: "#ffffff" # Background color for Android adaptive icons
  adaptive_icon_foreground: "icon.png" # Optional foreground image

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/onboarding1.png
    # - assets/onboarding2.png
    # - assets/onboarding3.png
