name: currencie_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  connectivity_plus: ^4.0.1
  flex_color_scheme: ^7.1.2
  animated_toggle_switch: ^0.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/onboarding1.png
    # - assets/onboarding2.png
    # - assets/onboarding3.png
